### ISSUE TITLE
Issue with Centering Image. 

### ISSUE THREAD

**Issue by Clyons1** [mdn/beginner-html-site-styled#1]
Hello,

I am currently beginning the Odin Project and have progressed to the CSS basics portion. Following this guide (https://developer.mozilla.org/en-US/Learn/Getting_started_with_the_web/CSS_basics) I have had great success and fun building a rudimentary webpage! However, I am unable to make the image I used centered, or even fit properly. I have copied and pasted the code from here after trying my own code and the issue still persists. While this is not the "end of the world" I am still curious how to fix this for future reference. 

Regardless of what I do to that Margin in css it never seems to affect the image on the web page. Does anyone have any insight as to how I can fix this?

Thank you for your time!

**Comment by chrisdavidmills** [comment]
Hi there! Glad you're enjoying the course. So, you're having trouble with this section:

https://developer.mozilla.org/en-US/Learn/Getting_started_with_the_web/CSS_basics#Centering_the_image

?

I'm assuming you've added the rule shown at the top of this section to your CSS?

So, is the image file itself really massive? This could be an issue, as my wording assume that you're using an image smaller than the width of its container. To rectify this, you could:

1. Reduce the image's width using a graphics package such as Photoshop or whatever. As shown in https://developer.mozilla.org/en-US/Learn/Getting_started_with_the_web/CSS_basics#Sorting_the_body_out, we've made the body element 600px wide, so less than 600px would be good.

2. Size the image using CSS; you could do this by adding a width property to the img rule, for example

img {
  display: block;
  margin: 0 auto;
  width: 400px;
}

Hope this helps; let me know how you get on.

**Comment by Tusharmalik** [comment]
i think that this issue can be closed now

**Comment by jdblischak** [comment]
> So, is the image file itself really massive? This could be an issue, as my wording assumes that you're using an image smaller than the width of its container (I should clarify this in the text).

I added a Note to the tutorial that summarizes the advice from @chrisdavidmills above.

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics$revision/1414509

**Comment by chrisdavidmills** [comment]
@jdblischak thanks for adding this bit of advice to the article — this is helpful. I've given it a copy edit, and now it is good to go.

**Comment by jdblischak** [comment]
Thanks @chrisdavidmills for the improvement!

The only nitpick I have is that I think the following statement is a bit misleading:

> If your image is larger, then it will take up the whole width of the body.

This makes it sound like the image will only take up the whole width of the body, i.e. be reduced to a maximum width of the width of the body. At least with my setup, my large image not only took up the whole width of the body but extended past it.

**Comment by chrisdavidmills** [comment]
@jdblischak good point; I've corrected the wording.
