### ISSUE TITLE
Giving margins

### ISSUE THREAD

**Issue by shahkv95** [mdn/beginner-html-site-styled#14]
I would like to improve the page by giving proper margins to the page so that it doesn't hurts human eyes. Space has always been a favourite tool for designers.

**Comment by shahkv95** [comment]
Can I work on this issue?

**Comment by shahkv95** [comment]
@chrisdavidmills

**Comment by chrisdavidmills** [comment]
I am not against this; more whitespace is usually a good thing, but if you did do this you'd need to make sure the scripted version of the site is updated too:

https://github.com/mdn/beginner-html-site-scripted

And the CSS tutorial that accompanies it is also updated:

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics

**Comment by avivmu** [comment]
Hey @shahkv95 are you still interested in working on this? if not please close this issue

**Comment by chrisdavidmills** [comment]
I think this has been inactive for long enough to close.
