### ISSUE TITLE
Adding Favicon 

### ISSUE THREAD

**Issue by VaibhavSharma24** [mdn/beginner-html-site-styled#61]
I would like to add a cool and amazing favicon to this site and i will ensure to follow your designs can you assign me this

**Comment by davmut69** [comment]
Hi,

Is this for my Google website under construction? If so, let me know what
you would like me to do.

Thank you.
David.

**Comment by jaissumi1402** [comment]
Can I add favicon your site.  Please assign this task to me

**Comment by iammanishk** [comment]
Hi, i would love  to add favicon. Can you assign me?

**Comment by caugner** [comment]
Thank you for your suggestion, and sorry for taking so long to respond.

This example site exists for the [accompanying MDN article](https://github.com/mdn/beginner-html-site-styled), which doesn't introduce the concept of favicons. Therefore it doesn't make sense at this time to add a favicon to the site.

Thanks again! 🙏
