### ISSUE TITLE
how to associate HTML pages with CSS on github

### ISSUE THREAD

**Issue by moorema** [mdn/beginner-html-site-styled#7]
I just started learning how to associate HTML pages with CSS on github.
 Thank you for your time

**Comment by chrisdavidmills** [comment]
Cool, let me know if you need any help.

**Comment by moorema** [comment]
Thank you, it has been solved. Because I just started to use github, the upload path of CSS was wrong, and it is normal after modification
I learned a lot through,developer.mozilla.org content is very good
Thank you again
