### ISSUE TITLE
Theming context menu of Firefox

### ISSUE THREAD

**Issue by wealstarrr** [mdn/beginner-html-site-styled#83]
Hello,

I'm no coder, using color.firefox.com to make themes. I couldn't find the elements to theme the browser's context menu ? There re properties for popup menu but they only work for the menus from the toolbar, not context menu.

How can I do this ?

Any help will be greatly appreciated.

**Comment by wealstarrr** [comment]
Update: Tooltips are also not themed.

**Comment by pepelsbey** [comment]
Hey! Context menus and tooltips are a part of system UI and they are not stylable. Also, this repository is not the right place for such questions. I’d suggest asking questions [on Reddit](https://www.reddit.com/r/firefox/), for example.
